try {
    //
    throw new Error('Deu um problema do c√≥digo')
} catch (e) {
    console.log(e.name + ':' + e.message)
}
